### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by BastianZim** [pasztorpisti/json-cfg#16]
Hi,

I would like to add this package to conda and just wanted to verify the supported python versions. From the releases I can see that the minimum is `python >=2.6` and according to the classifiers, python3 support starts at `3.3`, is that correct?

Thanks

Reference:

- https://github.com/pasztorpisti/json-cfg/releases/tag/v0.4.2-beta
- https://github.com/pasztorpisti/json-cfg/blob/0ccde013987910f2bb37a46788c0b8d3053a9ac6/setup.py#L47-L62

**Comment by BastianZim** [comment]
I also opened this issue in https://github.com/pasztorpisti/kwonly-args/issues/1 since this depends on kwonly-args.

**Comment by pasztorpisti** [comment]
Hi @BastianZim 

If you want to figure out if a specific version of this library works with a given python version then try running the tests on that python version.

IMO trying to support python versions that reached the end of their lives isn't necessarily the best way to invest your time:

- https://devguide.python.org/devcycle/#end-of-life-branches
- https://devguide.python.org/#status-of-python-branches

**Comment by BastianZim** [comment]
Hi @pasztorpisti 

ahh sorry, I should've formulated it differently, my apologies. Conda-forge officially supports only `python  >=3.6` which is also tested but allows packages to be made available for other versions too if there aren't any obvious obstacles that would prevent using them. This is just a service to the downloader but is not supported and any issues won't be fixed (Sort of like what you did with https://github.com/pasztorpisti/json-cfg/releases/tag/v0.4.2-beta). 
So this was more along the lines of "Is there anything obvious that you know of that would prevent a specific python version" and not about actual, official support. 

I have now added both packages at https://github.com/conda-forge/json-cfg-feedstock and https://github.com/conda-forge/kwonly-args-feedstock.

Let me know if you would like to be added as a maintainer there or would like me to add download instructions or badges here, otherwise feel free to just close both issues. Thanks for your help!

**Comment by pasztorpisti** [comment]
Sorry for not being able to provide more help. These libraries haven't changed much since the initial implementation so I wouldn't be surprised if they worked with some of the ancient python versions. However, I don't remember what the situation was 5+ years ago when I implemented these packages.

I know that they work with the current "alive" versions of CPython (3.6 - 3.9) and also with the versions mention in the `.travis.yml` file (CPython 2.7, 3.4+ , pypy, pypy3).

The best way to figure out package compatibility is always running the test suite because some python implementations (and in some cases their platform-dependent builds) have their own quirks.

**Comment by BastianZim** [comment]
No, you actually helped a lot, thank you very much! It really was only about if there is something major that you might be aware of, anything else is being tested or up to the person downloading the library. 

Thank you very much for your help and for creating the libraries in the first place! 😄
